### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Guillermo4060** [beihu235/FNF-NovaFlare-Engine#1]
### Describe your bug here.

Why does some mods show this error at the time of loading? They are more or less recent mods 
![Screenshot_20240324-095712_Friday Night Funkin' NovaFlare Engine](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/100426962/4e2d0c2b-b824-40d3-8e0c-204091641918)
![Screenshot_20240324-095942_Friday Night Funkin' NovaFlare Engine](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/100426962/da5e5ffe-31af-4591-b189-f09ae145b04f)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by beihu235** [comment]
Does it happen in probability or every time？

**Comment by Guillermo4060** [comment]
@beihu235 It always happens when you load a song from a mod, for example that one from the gifanny and others at the time of loading it releases that error and takes me out of the game

**Comment by beihu235** [comment]
Are you sure your assets files are in order
![Screenshot_20240325_062034](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/105789304/4ff679b3-48f3-4c54-9ba3-c56f6f48e376)

**Comment by beihu235** [comment]
The problem you reported is because the first one is missing ogg file and the second one is missing xml, which is not a normal error

**Comment by AlanGamer23XD** [comment]
El juego no deja abrir

**Comment by ZacXlmao** [comment]
There is a bug that in some songs the instrumental and the voices do not sound synchronized, for example the song toyboy sounds similar, or various mods

**Comment by beihu235** [comment]
> 有一个错误，在某些歌曲中，乐器和声音听起来不同步，例如歌曲“toyboy”听起来相似，或者各种mod

If the number of frames is not stable when the music starts playing, this will cause vocal delay, which I also found after the release of v1.1.0

**Comment by beihu235** [comment]
Why is everyone reporting mistakes here
