### ISSUE TITLE
Some Old Luas In 1.1.1 Don't Work

### ISSUE THREAD

**Issue by DARKTORTA** [beihu235/FNF-NovaFlare-Engine#10]
### Describe your bug here.

In 1.1.0 Almost all the old luas worked, Something that no longer works in 1.1.1, example: "Chromatic Abberation" or some lua shaders like that, don't work at all. (in 1.1.0 they worked perfectly) And some other luas

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, its normal version of 1.1.1

**Comment by beihu235** [comment]
Try replacing version at option

**Comment by DARKTORTA** [comment]
I already try it, and it's not fixed :[

**Comment by DARKTORTA** [comment]
Oh wait, i reset the Game and it's now fixed, thank you so much

**Comment by DARKTORTA** [comment]
Yes... some work but Others only fill my screen with red messages, in 1.1.0 it reproduced the Sscrips better, example: "Sscript it's a unknown variable" some things like that.

**Comment by beihu235** [comment]
use hscript version,But I seem to have messed up the hscript version

**Comment by Hola234tobotos** [comment]
Hi

**Comment by beihu235** [comment]
> 是的......有些工作，但其他人只用红色消息填充我的屏幕，在 1.1.0 中它更好地再现了 Sscrips，例如：“Sscript 这是一个未知变量”之类的东西。

The code has been returned to v1.1.0

**Comment by DARKTORTA** [comment]
Kk!, thanks you
