### ISSUE TITLE
EXTERNAL版本无法运行

### ISSUE THREAD

**Issue by 161978** [beihu235/FNF-NovaFlare-Engine#11]
### Describe your bug here.

第一次运行出现图一这种情况
![Screenshot_20240407_061756](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/122792113/c41447fc-21dd-4bbd-9b40-4ee8cbf95cd7)
后面运行直接闪退（已正确给予存储权限）

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by beihu235** [comment]
system not support
