### ISSUE TITLE
Key binds crash 

### ISSUE THREAD

**Issue by BCKgood** [beihu235/FNF-NovaFlare-Engine#12]
### Describe your bug here.

hi you can solve the problem of key bind options,the option crash for presing the button of the gamepad
Null Object Reference

options/base/ControlsSubState.hx [line 515] options/base/ControlsSubState.hx [line 285]

flixel/FlxState.hx [line 239]

flixel/FlxState.hx [line 248]

flixel/FlxGame.hx [line 749]

flixel/FixGame.hx [line 679]

flixel/FlxGame.hx [line 558]

openfl/events/EventDispatcher.hx [line 426]

openfl/display/DisplayObject.hx [line 1398]

### Crash Log or logcat logs (if existing)

```bash
Null Object Reference

options/base/ControlsSubState.hx [line 515] options/base/ControlsSubState.hx [line 285]

flixel/FlxState.hx [line 239]

flixel/FlxState.hx [line 248]

flixel/FlxGame.hx [line 749]

flixel/FixGame.hx [line 679]

flixel/FlxGame.hx [line 558]

openfl/events/EventDispatcher.hx [line 426]

openfl/display/DisplayObject.hx [line 1398]
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I'am not edit

**Comment by BCKgood** [comment]
![Screenshot_20240404_225302](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/141386926/f8b599b7-3e68-4801-b69d-1cb83171713d)
![Screenshot_20240404_225302](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/141386926/ddb5acfe-082d-4b98-b456-cab181023d09)

**Comment by beihu235** [comment]
The problem is resolved. Please wait for v1.1.2

**Comment by BCKgood** [comment]
What day will you upload it?

**Comment by beihu235** [comment]
https://github.com/beihu235/FNF-NovaFlare-Engine/actions/runs/8589652414

wait 10 mins

**Comment by BCKgood** [comment]
Thanks i love you 💕 💜  good engine

**Comment by BCKgood** [comment]
where can I download 1.1.2

**Comment by beihu235** [comment]
https://github.com/beihu235/FNF-NovaFlare-Engine/actions/runs/8589652414

**Comment by BCKgood** [comment]
I am from android i can't edit haxe

**Comment by BCKgood** [comment]
make an apk please

**Comment by beihu235** [comment]
Can't you see the download down there?

**Comment by BCKgood** [comment]
No

**Comment by beihu235** [comment]
![Screenshot_20240408_003301](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/105789304/8d6e6243-5d92-47fe-9837-695c9617f147)

**Comment by BCKgood** [comment]
It was my browser, sorry hahaha 😅😅

**Comment by BCKgood** [comment]
Hello, I can't enter the game, it crashes.
