### ISSUE TITLE
Pressing CTRL in the Keyboard Controls menu crashes the engine

### ISSUE THREAD

**Issue by JordanSantiagoYT** [beihu235/FNF-NovaFlare-Engine#13]
### Describe your bug here.

When in the Keybind Controls menu, pressing CTRL will crash the engine.

https://github.com/beihu235/FNF-NovaFlare-Engine/assets/61796448/5a77f7d3-04d3-4ec1-8441-2e35dfdcc033

### Crash Log or logcat logs (if existing)

```bash
Null Object Reference
options/base/ControlsSubState.hx [line 515]
options/base/ControlsSubState.hx [line 285]
flixel/FlxState.hx [line 239]
flixel/FlxState.hx [line 248]
flixel/FlxGame.hx [line 749]
flixel/FlxGame.hx [line 679]
flixel/FlxGame.hx [line 558]
openfl/events/EventDispatcher.hx [line 426]
openfl/display/DisplayObject.hx [line 1398]
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i used the downloaded build

**Comment by Stefan2008Git** [comment]
😭

**Comment by beihu235** [comment]
![Screenshot_20240407_215523](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/105789304/1c7f251b-9909-4f94-8d97-130f5b4de442)
wired problem

**Comment by beihu235** [comment]
The problem is resolved. Please wait for v1.1.2

**Comment by beihu235** [comment]
https://github.com/beihu235/FNF-NovaFlare-Engine/actions/runs/8589652414
