### ISSUE TITLE
bug issues from the pixel notes

### ISSUE THREAD

**Issue by Hmmloljacob1** [beihu235/FNF-NovaFlare-Engine#16]
### Describe your bug here.

so my noteskin is stepmania and i was checking the pixel notes and the notes crashed  
even in the week 6

### Crash Log or logcat logs (if existing)

```bash
yea crash
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

.

**Comment by beihu235** [comment]
Thank you for your report. I'll fix it right away
