### ISSUE TITLE
some mods crashes

### ISSUE THREAD

**Issue by Hmmloljacob1** [beihu235/FNF-NovaFlare-Engine#17]
### Describe your bug here.

i tried final zone confronting your self mod and it crashed 

### Crash Log or logcat logs (if existing)

```bash
yea some mods crash
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

.

**Comment by beihu235** [comment]
How much ram is your phone

**Comment by Hmmloljacob1** [comment]
4 ram?

**Comment by beihu235** [comment]
It's not unusual for games to crash due to lack of ram

**Comment by Hmmloljacob1** [comment]
wait i now now freeplay it didn't crashed
