### ISSUE TITLE
NovaFlare not opening 

### ISSUE THREAD

**Issue by Player1255** [beihu235/FNF-NovaFlare-Engine#18]
### Describe your bug here.

When I install it and allow it to get access to my files so I can put the mods, when I open it, it closes,I open it over and over, but it didn't work, I even reset it and unstall it and reinstall but nothing work so please can you fix the problem?

https://github.com/beihu235/FNF-NovaFlare-Engine/assets/101855847/4621211e-c4ec-4423-8b07-cb3861ac5c6d

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not edit anything

**Comment by Player1255** [comment]
I forgot to put "I install the external version"

**Comment by DARKTORTA** [comment]
Try putting "assets" folder by yourself

**Comment by beihu235** [comment]
wait v1.1.2 version

**Comment by Player1255** [comment]
> Try putting "assets" folder by yourself

I did 5 time but nothing is working

**Comment by Josephmorale** [comment]
fix shaders in NF Engine shaders not working for my phone android 15 armv8a aerch64 plisss! Fix it shaders crash on me!
