### ISSUE TITLE
Some shaders lag the game

### ISSUE THREAD

**Issue by DARKTORTA** [beihu235/FNF-NovaFlare-Engine#19]
### Describe your bug here.

In NovaFlare, some shaders make the gameplay so laggy, in original psych 0.7.3 or 0.6.3 this not happens (i play in 120 FPS, and FPS go down to 50 or 40, The same thing happens if I play at 60 FPS)
![Screenshot_2024-04-16-20-37-49-579_com google android apps photos-edit](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/109389983/b3a48b3a-7b5b-49df-910a-6636a9772472)
![Screenshot_2024-04-16-20-39-30-079_com NFengine-edit](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/109389983/ae4d9abf-6117-4892-88ea-ffb9bb01c99b)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by beihu235** [comment]
Is there a possibility that your version can not open this shader

**Comment by DARKTORTA** [comment]
The shader opens perfectly but it lag My gameplay :[

**Comment by beihu235** [comment]
shader takes a lot of load on its own，its normal thing

**Comment by DARKTORTA** [comment]
Oh, ok thx
