### ISSUE TITLE
Extra Control issues

### ISSUE THREAD

**Issue by SK7580** [beihu235/FNF-NovaFlare-Engine#2]
### Describe your bug here.

Whenever I pressed 'B', it just give me an error after I try to change my controls.
![Screenshot_20240325_104515](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/134719321/c247bc70-c155-4f41-a2eb-3461f062c3b0)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not.

**Comment by beihu235** [comment]
![Screenshot_2024_0325_221745](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/105789304/87d3ee1f-b216-4e86-9a5c-8ff180d7122c)
