### ISSUE TITLE
FIX WEEK 6 PIXEL NOTES PLS

### ISSUE THREAD

**Issue by Denyscrasav4ik** [beihu235/FNF-NovaFlare-Engine#21]
### Describe your bug here.

when I enter week 6 instead of normal pixel notes I see Haxe placeholder icons and when i press any button it crashes
(by the way im playing on v1.1.2 beta build maybe there is no this issue on v1.1.1 release build)

### Crash Log or logcat logs (if existing)

[2024-04-22-13'57'55.txt](https://github.com/beihu235/FNF-NovaFlare-Engine/files/15061810/2024-04-22-13.57.55.txt)

### What is your build target?

Desktop (Linux, Windows or Mac)

**Comment by Denyscrasav4ik** [comment]
here is link with the video
https://s3.filebin.net/filebin/e5e77cb610908bbbef6563f05f2d3f40718dacf1c1173c4e0a3c6b4bd3ad7634/4f753a838404f32d49d4c2904cb58a0c0de2b9829f9e7b8497742f1562900a82?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=7pMj6hGeoKewqmMQILjm%2F20240422%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240422T111451Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&response-cache-control=max-age%3D300&response-content-disposition=filename%3D%222024-04-22_14-04-45.mp4%22&response-content-type=video%2Fmp4&X-Amz-Signature=fb11c35b0a652232f1e362e7c8edc15413ee54e2f1260ebeb26c95942f3a4f2a

**Comment by beihu235** [comment]
The problem has been reported, and it's been fixed

**Comment by beihu235** [comment]
wired bug but real

**Comment by Denyscrasav4ik** [comment]
please let me know when its fixed because i want to get all awards

**Comment by beihu235** [comment]
maybe tomorrow?

**Comment by Denyscrasav4ik** [comment]
ok

**Comment by Denyscrasav4ik** [comment]
the bug is almost fixed but on first song of the week arrows that fall are "placeholdered" but atleast you can beat it the week (on other songs of the week is normal)

**Comment by beihu235** [comment]
because note.hx not fix yet

**Comment by beihu235** [comment]
maybe it work well now
