### ISSUE TITLE
Splashes not always splash when you get sick/marvelous

### ISSUE THREAD

**Issue by Denyscrasav4ik** [beihu235/FNF-NovaFlare-Engine#23]
### Describe your bug here.

Splashes not always splash when you get sick/marvelous

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

/

**Comment by beihu235** [comment]
It did get broken in one of the v1.1.2 updates, I will fix it

**Comment by beihu235** [comment]
fixed
