### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by coolArthur3210** [beihu235/FNF-NovaFlare-Engine#24]
### Describe your bug here.

Every time I try to enter the game is just crashing

### Crash Log or logcat logs (if existing)

```bash
No response :C
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit

**Comment by beihu235** [comment]
wait v1.1.2
