### ISSUE TITLE
Freeplay menu is SLOW

### ISSUE THREAD

**Issue by MarddleDoo12** [beihu235/FNF-NovaFlare-Engine#25]
### Describe your bug here.

The game runs surprisingly smoothly for me, (and I always use optimized versions of the engines) even though I only have 3GB of RAM, but the **freeplay menu works really badly** for me, everything slows down, When selecting (gameplay changer) it takes me to the section to search for songs, and I don't know, if there is any way to fix this, I would appreciate it if you told me.

Thanks in advance for taking the time to read this.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i just installed the Android-Data build from releases

**Comment by beihu235** [comment]
normal, because optimized is bad

**Comment by MarddleDoo12** [comment]
Eh, but the freeplay problem is in the non-optimized version (there is not even a low end of NF engine 1.1.1) the one I am using is the "Android-DATA.zip" version from Releases

**Comment by MarddleDoo12** [comment]
Is the issue closed?
