### ISSUE TITLE
There's an error when getting to the compile section when building

### ISSUE THREAD

**Issue by XdgamerZ38** [beihu235/FNF-NovaFlare-Engine#3]
### Describe your problem here.

There's an error when getting to the compile section when building
Build target is pc windows and android

### Are you modding a build from source or with Lua?

Lua and Source

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by beihu235** [comment]
hmm.json is now running properly

**Comment by XdgamerZ38** [comment]
Lemme try

**Comment by XdgamerZ38** [comment]
It doesn't work
![Screenshot_20240326_151856_Chrome](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/116748774/58a82b83-928f-42d0-8718-6929d1731cd0)

**Comment by beihu235** [comment]
mine flixel lib have problem, use official version

**Comment by XdgamerZ38** [comment]
How

**Comment by beihu235** [comment]
![Screenshot_20240326_230359](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/105789304/523f1fc4-cb34-4f05-acb5-71c425474f30)
