### ISSUE TITLE
Null Object Reference on Main Menu (Windows)

### ISSUE THREAD

**Issue by SkylaLZ** [beihu235/FNF-NovaFlare-Engine#32]
### Describe your bug here.

Game will immediately crash once pressing enter on the main menu.

https://github.com/beihu235/FNF-NovaFlare-Engine/assets/142008315/4917be4d-b812-4b87-8fdc-c6c8cd036135

### Crash Log or logcat logs (if existing)

```bash
Null Object Reference
states/MainMenuState.update() [line 361]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 750]
flixel/FlxGame.step() [line 680]
flixel/FlxGame.onEnterFrame() [line 559]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
```

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

No

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by beihu235** [comment]
fixed,download again
