### ISSUE TITLE
Audio delayed 

### ISSUE THREAD

**Issue by DAVIDJ024** [beihu235/FNF-NovaFlare-Engine#33]
### Describe your bug here.

Hello, I wanted to tell you that I have a small problem, when I downloaded the game, which took a few minutes, I tried to play but the game's audio sounded strange, like it was delayed, I wanted to know if you could fix it, since when I play it is uncomfortable to hear the song with a delay.

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Not yet I just opened the game

**Comment by beihu235** [comment]
upload a video
