### ISSUE TITLE
Pixel notes don't work in 1.1.3

### ISSUE THREAD

**Issue by DARKTORTA** [beihu235/FNF-NovaFlare-Engine#34]
### Describe your bug here.

Songs: example: prey from sonic.exe, week 6, or any other mods, pixel notes don't loads and it crash or simply notes are buged

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

No

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by DARKTORTA** [comment]
Since 1.1.2 pixel notes do not work

**Comment by DARKTORTA** [comment]
Look, let me send you a screenshot

**Comment by DARKTORTA** [comment]
Well, here is a video 

https://github.com/beihu235/FNF-NovaFlare-Engine/assets/109389983/e13a188e-d98b-45f6-a502-c7f6c3a51973

**Comment by beihu235** [comment]
Can you show me where the image are so I can fix them

**Comment by DARKTORTA** [comment]
This?
![Screenshot_2024-05-19-09-21-37-653_ru zdevs zarchiver](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/109389983/0011123b-6446-494e-b0ec-4c8a8b1d8f96)

**Comment by beihu235** [comment]
try this version if work well close this issue
https://github.com/beihu235/FNF-NovaFlare-Engine/actions/runs/9147106875

**Comment by DARKTORTA** [comment]
Thanks, let me test it

**Comment by DARKTORTA** [comment]
The Bug remains, when I press a note it crashes 
![Screenshot_2024-05-19-13-38-01-348_com NovaFlareEngine](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/109389983/38f78247-4432-4cff-8abb-e4c5b1f063d7)

**Comment by beihu235** [comment]
try again
https://github.com/beihu235/FNF-NovaFlare-Engine/actions/runs/9148785607

**Comment by DARKTORTA** [comment]
Now it works perfectly!, the only issue but It's not serious It's pixel notes in week 6 when a note make a hit, anyway, thanks you so much
![Screenshot_2024-05-19-20-10-02-480_com NovaFlareEngine](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/109389983/4cba63a5-4b97-49b5-8773-a7fd4f248107)

**Comment by beihu235** [comment]
In fact, I don't understand why pixel cut head problems, but just restart can solve this problem

**Comment by DARKTORTA** [comment]
Restart don't solve week 6 pixel notes :[ but hey now it works and don't crash i'm other songs with pixel playstate
