### ISSUE TITLE
Sometimes freeplay dont load

### ISSUE THREAD

**Issue by DARKTORTA** [beihu235/FNF-NovaFlare-Engine#35]
### Describe your bug here.

Sorry for many request, but look
![Screenshot_2024-05-20-16-11-46-426_com NovaFlareEngine](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/109389983/e44fe4c8-930c-4fb0-9bec-6322382ea520)

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didnt

**Comment by beihu235** [comment]
Incorrect case

**Comment by beihu235** [comment]
The nf engine and psych are a little different for shop detection, and there is no better way to go back to the original version
