### ISSUE TITLE
When loading the most recent version (v1.1.4) it claims that the version before is the most recent update

### ISSUE THREAD

**Issue by PrimisRulz** [beihu235/FNF-NovaFlare-Engine#37]
### Describe your bug here.

I booted up the game, and the "out of date" message appeared, however it said that V1.1.3 was the most recent version.

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

No

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just installed this for the first time.

**Comment by beihu235** [comment]
v 1.1.4 just test
