### ISSUE TITLE
Gf layers in week 4

### ISSUE THREAD

**Issue by abod-ev** [beihu235/FNF-NovaFlare-Engine#39]
### Describe your bug here.

When u open week 4 gf layer got on top of all layers of the map
![Screenshot_2024-07-05-16-54-57-43_e2ea35751c0006446b45ca8b515b31cd](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/172452263/60e820c4-0e0f-4071-ba07-4da89539e4b2)

### Are you modding a build from source or with Lua?

Lua

### Have you open preload state?

Yes

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the watermark paint it's in the picture

**Comment by beihu235** [comment]
psych engine bug.I also have no idea fix
