### ISSUE TITLE
Problems with multitap / multitouch

### ISSUE THREAD

**Issue by NanoDevES** [beihu235/FNF-NovaFlare-Engine#4]
### Describe your bug here.

I don't know if this is even possible to fix but seeing the things you've been able to do with the engine I think You don't lose anything by trying, right?
There is a bug that has been present for a long time in the original engine/port that causes simultaneously pressing several arrows at the same time with the touch screen is  
sometimes counterproductive, sometimes making triples or quadruples is not possible because the imput does not correctly detect the touch, I don't know if I explained correctly 

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by beihu235** [comment]
Your phone doesn't support multi-touch
