### ISSUE TITLE
No animation note is not working

### ISSUE THREAD

**Issue by Licuatronix** [beihu235/FNF-NovaFlare-Engine#42]
### Describe your bug here.

well the title explains itself, basically the custom note "no animation" is not working, i try to use a mod that already use it and also i manually add the note with the chart editor, but the character still does the animation, i only test it on android idk if happends on ios or pc

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Is the default build, no changes

**Comment by beihu235** [comment]
fixed
