### ISSUE TITLE
Aren't they supposed to be down?

### ISSUE THREAD

**Issue by DAVIDJ024** [beihu235/FNF-NovaFlare-Engine#43]
![Screenshot_20240708-164848.jpg](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/169626760/7cb5ef7f-8031-486b-ac00-6df0969feb75)

**Comment by DAVIDJ024** [comment]
I tried to scroll it on editors and then closed by itself.

**Comment by beihu235** [comment]
will fix
