### ISSUE TITLE
Notes skin don't work will 

### ISSUE THREAD

**Issue by abod-ev** [beihu235/FNF-NovaFlare-Engine#44]
### Describe your problem here.

When I put custom notes and want to put in chart the note load skin load for first time but in second time don't work the skin and the BOTPLAY should not press that not he should leave the note pass but it takes it and notes skin load in one note and the other looks default note skin so I test that code I did to psych engine and the notes work so I think that from nf engine it self 

### Are you modding a build from source or with Lua?

Lua

### Have you open preload state?

No

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No just put script change the window name in pc

**Comment by beihu235** [comment]
Unable to understand, please record a video
