### ISSUE TITLE
Cant install EXTERNAL and DATA

### ISSUE THREAD

**Issue by Midgames0010** [beihu235/FNF-NovaFlare-Engine#45]
### Describe your problem here.

I was trying to install the novaflare but when i do it, it says "A error as occured during the installation.". What's wrong?

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

**Comment by beihu235** [comment]
android system problem?

**Comment by Midgames0010** [comment]
When i tried to open the novaflora after installed it, it just closes
himself.

Em sáb, 20 de jul de 2024 09:12, 北狐丶逐梦 ***@***.***> escreveu:

**Comment by Midgames0010** [comment]
Sorry for the late response

Em qua, 24 de jul de 2024 22:15, acesso meninos novais <
***@***.***> escreveu:

**Comment by Midgames0010** [comment]
Great!

Em seg, 26 de ago de 2024 16:50, 北狐丶逐梦 ***@***.***> escreveu:
