### ISSUE TITLE
引擎的lua源码适配

### ISSUE THREAD

**Issue by Wqawa** [beihu235/FNF-NovaFlare-Engine#46]
### What is your question?

我想问一下，既然NFE是基于PE0.7+，并且在bilibili上说了lua兼容，我问一下，具体兼容到什么地步，有什么问题，目前的问题会在1.1.4以后修吗？

**Comment by beihu235** [comment]
lua的话目前除了healthbar有关的那块还没修，其他没问题可以兼容到psych0.5甚至更低，runhaxecode可以去设置调整版本以支持0.6.x的代码
