### ISSUE TITLE
Chart Editor Character select Issue

### ISSUE THREAD

**Issue by MrLightProgrammer** [beihu235/FNF-NovaFlare-Engine#48]
[###]() Describe your bug here.

Well some times i like put skins mods in mobile version, but the character list of the chart editor is like this, and i can't scroll up or down (if i have more skins). 

I can select another skin, but only the one that is already in front of me, as if I couldn't scroll up and down, as I said before.

![Screenshot_2024-07-24-02-07-22-713_com miui gallery](https://github.com/user-attachments/assets/fe349bbf-34a9-4cd7-9520-e85136371bde)

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by beihu235** [comment]
it will fix
