### ISSUE TITLE
Error in Compiling the game

### ISSUE THREAD

**Issue by S4rcky** [beihu235/FNF-NovaFlare-Engine#49]
### Describe your problem here.

I was trying to compile the nova flare engine and this happened to me, can someone help me fix this?
![image](https://github.com/user-attachments/assets/aa4bc6ca-78b2-4362-bd74-3883b3410a5b)

### Are you modding a build from source or with Lua?

Source

### Have you open preload state?

Yes

### What is your build target?

Desktop (Linux, Windows or Mac)

**Comment by S4rcky** [comment]
i installed

**Comment by S4rcky** [comment]
and not works

**Comment by beihu235** [comment]
Try to remove and reinstall the hmm version

**Comment by S4rcky** [comment]
![image](https://github.com/user-attachments/assets/2842c445-59e6-42d8-926c-417fbdf4601c)
Its not working and yes i remove and reinstall the hmm version so i dont know

**Comment by Raphixxzy** [comment]
I have the same problem and I can't modify anything without getting an error in the androidbuild action.

**Comment by beihu235** [comment]
> 我遇到了同样的问题，我无法修改任何内容，否则 androidbuild 操作会出现错误。

so only androidbuild have this problem? how about windows build? is it fine?

**Comment by Raphixxzy** [comment]
I managed to solve this, I updated the Android tools git with the same link as the mobile porting repository and it works normally on my fork.

**Comment by beihu235** [comment]
so is androidtools problem

**Comment by Raphixxzy** [comment]
Exatamente
