### ISSUE TITLE
Song delay

### ISSUE THREAD

**Issue by CaketheIV** [beihu235/FNF-NovaFlare-Engine#5]
### Describe your bug here.

Didn't know if this was possible to fix
But when I use like a pair of wireless earphones and stuff
the apk delays the music, forcing me to not use earphones
Going to debug do not work either 

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not.

**Comment by beihu235** [comment]
The Infinity headset itself has a lag

**Comment by beihu235** [comment]
Try limited headphones
