### ISSUE TITLE
Error compiling NFE

### ISSUE THREAD

**Issue by crisjonas7** [beihu235/FNF-NovaFlare-Engine#50]
### Describe your problem here.

Well... I'm just will drop the error code here...

source/substates/ResultsScreen.hx:592: characters 10-18 : Warning : (WVarInit) Local variable swagRect might be used before being initialized
source/substates/ResultsScreen.hx:593: characters 7-15 : Warning : (WVarInit) Local variable swagRect might be used before being initialized
source/substates/ResultsScreen.hx:594: characters 10-18 : Warning : (WVarInit) Local variable swagRect might be used before being initialized
source/substates/ResultsScreen.hx:596: characters 14-22 : Warning : (WVarInit) Local variable swagRect might be used before being initialized
source/substates/ResultsScreen.hx:599: characters 11-19 : Warning : (WVarInit) Local variable swagRect might be used before being initialized
source/substates/ResultsScreen.hx:600: characters 11-19 : Warning : (WVarInit) Local variable swagRect might be used before being initialized
source/substates/ResultsScreen.hx:602: characters 25-33 : Warning : (WVarInit) Local variable swagRect might be used before being initialized
source/substates/ResultsScreen.hx:606: characters 11-21 : Warning : (WVarInit) Local variable timerTween might be used before being initialized
Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/3,0,2/src/vlc/LibVLCBuild.xml"

### Are you modding a build from source or with Lua?

Source

### Have you open preload state?

Yes

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by beihu235** [comment]
use hxCodec 2.6.0 because android highest support version is 2.6.0

**Comment by crisjonas7** [comment]
Oh thanks, but now I have another problem, lol ._.

source/backend/VideoHandler_Title.hx:14: characters 18-31 : Type not found : vlc.VLCBitmap
source/backend/VideoHandler_Title.hx:18: characters 34-43 : Type not found : VLCBitmap

**Comment by beihu235** [comment]
set hxCodec to 2.6.0 version
