### ISSUE TITLE
beat Snap don't work and zooming a more then 1/24 crash the game

### ISSUE THREAD

**Issue by abod-ev** [beihu235/FNF-NovaFlare-Engine#51]
### Describe your bug here.

when i try using beat snap in chart edtore don't work and when i zoom a lot a got this msg
![image](https://github.com/user-attachments/assets/c36309ad-53fd-4302-9c55-94762afc0fb1)

### Crash Log or logcat logs (if existing)

```bash
Null Object Reference
states/editors/ChartingState.reloadGridLayer() [line 2314]
states/editors/ChartingState.updateZoom() [line 2298]
states/editors/ChartingState.update() [line 1950]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 750]
flixel/FlxGame.step() [line 680]
flixel/FlxGame.onEnterFrame() [line 559]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
```

### Are you modding a build from source or with Lua?

Lua

### Have you open preload state?

No

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by beihu235** [comment]
The editor will be fixed in the future, but it will not be released at this time
