### ISSUE TITLE
iOS crash bug

### ISSUE THREAD

**Issue by mrchillguy1** [beihu235/FNF-NovaFlare-Engine#53]
### Describe your bug here.

When I try to open story mode or freeplay mode it crashes and gives me this message.
![IMG_0637](https://github.com/user-attachments/assets/de4533bf-cc28-4064-bcca-105baf783785)

### Are you modding a build from source or with Lua?

Lua

### Have you open preload state?

Yes

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

yes

**Comment by beihu235** [comment]
you forget put songs
