### ISSUE TITLE
Authorization Needing

### ISSUE THREAD

**Issue by UnknownJohn78** [beihu235/FNF-NovaFlare-Engine#54]
### What is your question?

The authorization needing keeps popping up I could not download this specific apk can you guys help me with the authorization needing?

**Comment by beihu235** [comment]
authorization for what

**Comment by UnknownJohn78** [comment]
When i download the NF engine it fails and says i need authorization

**Comment by UnknownJohn78** [comment]
How could i fix it?

**Comment by UnknownJohn78** [comment]
![Screenshot_20240826_120353](https://github.com/user-attachments/assets/52246d17-e2c3-45a5-bc80-77979382cec5)
This is the problem

**Comment by beihu235** [comment]
The problem with your own account maybe

**Comment by UnknownJohn78** [comment]
I can download any apk including zip but this one ain't

**Comment by UnknownJohn78** [comment]
Every 100+ mb it fails and says i need authorization?

**Comment by UnknownJohn78** [comment]
Including every NF android ones

**Comment by beihu235** [comment]
No one has ever had this problem, it can only be your account
