### ISSUE TITLE
Ya hice la carpeta .NovaFlare Engine pero me salta este error (los permisos ya se los di)

### ISSUE THREAD

**Issue by HUXULS** [beihu235/FNF-NovaFlare-Engine#57]
### Describe your bug here.

Descarge la 1.1.5 la instale Me salta error de que tiene mal las carpetas se lo acomodo y Pongo los assets de la 1.1.5 en su respectivo lugar y hago el .Nova.flora engine En sistema storage/0/ despues entro a la app y me sale el error (¡Error!No se obtiene el permiso, reinicie la aplicación) esta traducido al español espero que me puedan ayudar gracias

https://youtu.be/VmNSl2KG9Nk?si=fmIYv9r6PzLz1KRK

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

no cambie nada

**Comment by MaoPou** [comment]
1. Vaya a la administración de permisos, desactive todos los permisos de NF y póngalo en segundo plano
2. Abra NF, recuerde, no haga clic en ningún botón después de abrir
3. Cuelgue NF en segundo plano y vuelva a la administración de permisos
4. Otorga todos los permisos
5. Vuelva a NF haciendo clic en el botón
6. Entonces puedes divertirte

**Comment by MaoPou** [comment]
Si no funciona una vez, inténtalo de nuevo, este método nunca ha fallado en los jugadores chinos
