### ISSUE TITLE
About the Chart editor for select stuff 

### ISSUE THREAD

**Issue by MrLightProgrammer** [beihu235/FNF-NovaFlare-Engine#58]
### What is your question?

This new update is amazing and very well optimized for mobile version, but unfortunately the chart editor bug are still there.

When you try to scroll to select different options like events/characters/notes skins or any other thing, the Touchscreen of the mobile can't "scroll" these options correctly and the box options selector just disappear.

Why don't you guys make the chart editor like the same way the "options" are, i don't know if this takes a really long time, but just to make the chart editor more easy to edit for mobile users :).

THANSK FOR THE PORT!!!

**Comment by beihu235** [comment]
fixed
