### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by UnknownJohn78** [beihu235/FNF-NovaFlare-Engine#59]
### Describe your problem here.

I cant open i dont know why it keep popping up
![Screenshot_20240903_083355](https://github.com/user-attachments/assets/8d58f04a-14f1-4572-8050-b85ca71e04de)
And this
![Screenshot_20240903_083710](https://github.com/user-attachments/assets/f50f526f-5668-4ee6-bc99-b0a3b863cfad)

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

**Comment by MishaFNF** [comment]
BEIHU, JUST FIX THIS PLS

**Comment by kuyaaj0** [comment]
It just required some OG aka original parts from the assets and it's pretty easy to handle it and depends on your device

**Comment by kuyaaj0** [comment]
I've been encounter like that for couple weeks ago and already fixed it

**Comment by UnknownJohn78** [comment]
How did you do it?

**Comment by kuyaaj0** [comment]
You can check this one on YouTube https://youtu.be/uTbEtH-RY7o?si=ytW2aNoXuA-uCN-q

It's a tutorial about installation and fixing the error that you can't access and that video could work for you and if it's not working welp I tried

**Comment by beihu235** [comment]
try use v1.1.5-hotfix version
