### ISSUE TITLE
Chart editor beat snaping doesn't work

### ISSUE THREAD

**Issue by Heckatt** [beihu235/FNF-NovaFlare-Engine#62]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/b5b000b6-4053-4479-949b-827be3dad752)
![image](https://github.com/user-attachments/assets/9415d2cc-306f-4733-ab94-3f7b79a34477)
seems pretty straight forward, the beat snap doesn't do anything even with 16th or 192nd

### Are you modding a build from source or with Lua?

Lua and Source

### Have you open preload state?

Yes

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed language.hx and titlestate.hx

**Comment by beihu235** [comment]
psych already removed this function,use zoom in/out
