### ISSUE TITLE
The image doesn't appear in the freeplay

### ISSUE THREAD

**Issue by Contra-Sakar** [beihu235/FNF-NovaFlare-Engine#64]
### Describe your bug here.

![184 sin título_20241005001603](https://github.com/user-attachments/assets/09097781-6702-4b47-b2bc-d2f40e71a576)

I don't know why that's in black and doesn't appear like you showed in your YouTube video. I'm not sure if it's an error or if I need to do something for it to work.

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Don't modify anything

**Comment by MaoPou** [comment]
You need to go to the settings to switch the freeplay back to PE, go to freeplay, go back to the settings, and switch back to NF freeplay
