### ISSUE TITLE
Lua files get a error

### ISSUE THREAD

**Issue by Mikhailacer19** [beihu235/FNF-NovaFlare-Engine#66]
### Describe your bug here.

![Screenshot_20241012_172916](https://github.com/user-attachments/assets/af444e76-faa8-4b64-8c0b-530a94eecc3a)

This problem only occurs in the two hotfix versions

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

No

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't

**Comment by beihu235** [comment]
I think it was fixed
