### ISSUE TITLE
Note delay or song delay?!

### ISSUE THREAD

**Issue by kuyaaj0** [beihu235/FNF-NovaFlare-Engine#67]
### What is your question?

My question is that are you already done fixing the note delay when it comes to lag spikes or a bit long song and the note gets delay while the song plays since I got encounter that delay while playing the mod i was thinking that is it note delay or song delay so I was hoping to ask the question that is it already fixed or am I going to wait the next update?

**Comment by beihu235** [comment]
some version really have this problem, please try latest version
