### ISSUE TITLE
noteTweenScale code add-on request

### ISSUE THREAD

**Issue by kuyaaj0** [beihu235/FNF-NovaFlare-Engine#69]
### What is your question?

Hey beihu I was wondering on the next update that can you add the noteTweenScaling code from notes since the noteTweenX and noteTweenY are added on couple years ago when the psych engine Lua updated and the codes on noteTweenX and noteTweenY are on the funkinLua.hx on the psychlua folder and I was adding the noteTweenScale it kinda lag and slows the game when the duration are on 0.1 seconds so yea I was asking to you if you can add that code on the funkinLua.hx

Edited:
This is the example of the noteTweenScaling('idk', 0, scale-7, duration-0.1, 'ease')
Ok on the code I added that there is different between the pixel and not pixelated 

On the pixel scale that the original on scale is 7 and on the non pixelated the original scale is 0.7 kinda confusing on the pixel scale and the non pixelated scale

**Comment by beihu235** [comment]
already add this function now
