### ISSUE TITLE
Black boxes

### ISSUE THREAD

**Issue by Nightmare2005** [beihu235/FNF-NovaFlare-Engine#70]
### Describe your bug here.

In Nova flare engine 1.1.5 hotfix 3 the notes appear  as black boxes with and without mods

### Are you modding a build from source or with Lua?

Lua and Source

### Have you open preload state?

No

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No nothing was edited

**Comment by VanRF09** [comment]
We are the same, but have you tried changing the skin of the note? For me, sometimes when I use another skin note, then exit the game and re-enter it will become a black box again 🗿🗿

**Comment by beihu235** [comment]
fixed
