### ISSUE TITLE
noteTweenScale optimization?

### ISSUE THREAD

**Issue by kuyaaj0** [beihu235/FNF-NovaFlare-Engine#75]
### What is your question?

By the way beihu there is one major issue is the noteTweenScaling optimization part since I'm using the noteTweenScaling code for modchart I make but it lags out around 4-8 frames by second and here's the code I've been making a modchart 

function onStepHit()
    -- upper bounce left to right
    if curStep == 675 or curStep == 681 or curStep == 691 or curStep == 707 or curStep == 723 or curStep == 739 or curStep == 755 or curStep == 771 or curStep == 787 or curStep == 803 then
        noteTweenScale('playerScale', 4, 8.25, 1, 'smootherStepIn')
        noteTweenScale('playerScale2', 7, 8.25, 1, 'smootherStepIn')
        noteTweenX('left2', 4, 782, 0.1, 'smootherStepIn')
        noteTweenX('lefty2', 7, 1121, 0.1, 'smootherStepIn')
        noteTweenY('leftup', 4, 540, 0.1, 'smootherStepIn')
        noteTweenY('leftupd', 7, 540, 0.1, 'smootherStepIn')
        --opponent
        noteTweenScale('opponentScale', 0, 8.25, 1, 'smootherStepIn')
        noteTweenScale('opponentScale1', 3, 8.25, 1, 'smootherStepIn')
        noteTweenX('leftop', 0, 42, 0.1, 'smootherStepIn')
        noteTweenX('leftyop', 3, 381, 0.1, 'smootherStepIn')
        noteTweenY('leftupop', 0, 540, 0.1, 'smootherStepIn')
        noteTweenY('leftupops', 3, 540, 0.1, 'smootherStepIn')
    end

    -- going back to their original position
    if curStep == 676.9 or curStep == 682.9 or curStep == 692.9 or curStep == 708.9 or curStep == 724.9 or curStep == 740.9 or curStep == 756.9 or curStep == 772.9 or curStep == 788.9 or curStep == 804.9 then
        noteTweenScale('playerScale3', 4, 7, 1, 'smootherStepIn')
        noteTweenScale('playerScale4', 7, 7, 1, 'smootherStepIn')
        noteTweenX('left3', 4, 732, 0.2, 'smootherStepIn')
        noteTweenX('lefty3', 7, 1071, 0.2, 'smootherStepIn')
        noteTweenY('leftup3', 4, 570, 0.2, 'smootherStepIn')
        noteTweenY('leftup4', 7, 570, 0.2, 'smootherStepIn')
        --opponent
        noteTweenScale('opponentScale2', 0, 7, 1, 'smootherStepIn')
        noteTweenScale('opponentScale3', 3, 7, 1, 'smootherStepIn')
        noteTweenX('leftop', 0, 92, 0.2, 'smootherStepIn')
        noteTweenX('leftyop1', 3, 431, 0.2, 'smootherStepIn')
        noteTweenY('leftupop1', 0, 570, 0.2, 'smootherStepIn')
        noteTweenY('leftupops1', 3, 570, 0.2, 'smootherStepIn')
    end

    -- upper bounce down and up
    if curStep == 679 or curStep == 685 or curStep == 695 or curStep == 711 or curStep == 727 or curStep == 743 or curStep == 759 or curStep == 775 or curStep == 791 or curStep == 807 then
        noteTweenScale('playerScale5', 5, 8.25, 1, 'smootherStepIn')
        noteTweenScale('playerScale6', 6, 8.25, 1, 'smootherStepIn')
        noteTweenX('left2', 5, 895, 0.1, 'smootherStepIn')
        noteTweenX('lefty2', 6, 1008, 0.1, 'smootherStepIn')
        noteTweenY('leftup1', 5, 540, 0.1, 'smootherStepIn')
        noteTweenY('leftup2', 6, 540, 0.1, 'smootherStepIn')
        --opponent
        noteTweenScale('opponentScale4', 1, 8.25, 1, 'smootherStepIn')
        noteTweenScale('opponentScale5', 2, 8.25, 1, 'smootherStepIn')
        noteTweenX('leftop2', 1, 155, 0.1, 'smootherStepIn')
        noteTweenX('leftyop2', 2, 268, 0.1, 'smootherStepIn')
        noteTweenY('leftupop2', 1, 540, 0.1, 'smootherStepIn')
        noteTweenY('leftupops2', 2, 540, 0.1, 'smootherStepIn')
    end

    -- original position
    if curStep == 680.9 or curStep == 686.9 or curStep == 696.9 or curStep == 712.9 or curStep == 728.9 or curStep == 744.9 or curStep == 760.9 or curStep == 776.9 or curStep == 792.9 or curStep == 808.9 then
        noteTweenScale('playerScale6', 5, 7, 1, 'smootherStepIn')
        noteTweenScale('playerScale7', 6, 7, 1, 'smootherStepIn')
        noteTweenX('left4', 5, 845, 0.2, 'smootherStepIn')
        noteTweenX('lefty4', 6, 958, 0.2, 'smootherStepIn')
        noteTweenY('leftup5', 5, 570, 0.2, 'smootherStepIn')
        noteTweenY('leftup6', 6, 570, 0.2, 'smootherStepIn')
        --opponent
        noteTweenScale('opponentScale6', 1, 7, 1, 'smootherStepIn')
        noteTweenScale('opponentScale7', 2, 7, 1, 'smootherStepIn')
        noteTweenX('leftop3', 1, 205, 0.2, 'smootherStepIn')
        noteTweenX('leftyop3', 2, 318, 0.2, 'smootherStepIn')
        noteTweenY('leftupop3', 1, 570, 0.2, 'smootherStepIn')
        noteTweenY('leftupops3', 2, 570, 0.2, 'smootherStepIn')
    end

    -- lower bounce left and right
    if curStep == 683 or curStep == 689 or curStep == 699 or curStep == 715 or curStep == 731 or curStep == 747 or curStep == 763 or curStep == 779 or curStep == 795 then
        noteTweenScale('playerScale8', 4, 6, 1, 'smootherStepIn')
        noteTweenScale('playerScale9', 7, 6, 1, 'smootherStepIn')
        noteTweenX('left3', 4, 682, 0.1, 'smootherStepIn')
        noteTweenX('lefty3', 7, 1021, 0.1, 'smootherStepIn')
        noteTweenY('leftup7', 4, 590, 0.1, 'smootherStepIn')
        noteTweenY('leftup8', 7, 590, 0.1, 'smootherStepIn')
        --opponent
        noteTweenScale('opponentScale8', 0, 6, 1, 'smootherStepIn')
        noteTweenScale('opponentScale9', 3, 6, 1, 'smootherStepIn')
        noteTweenX('leftop4', 0, 142, 0.1, 'smootherStepIn')
        noteTweenX('leftyop4', 3, 481, 0.1, 'smootherStepIn')
        noteTweenY('leftupop4', 0, 590, 0.1, 'smootherStepIn')
        noteTweenY('leftupops4', 3, 590, 0.1, 'smootherStepIn')
    end

    -- original position
    if curStep == 684.9 or curStep == 690.9 or curStep == 700.9 or curStep == 716.9 or curStep == 732.9 or curStep == 748.9 or curStep == 764.9 or curStep == 780.9 or curStep == 796.9 then
        noteTweenScale('playerScale10', 4, 7, 1, 'smootherStepIn')
        noteTweenScale('playerScale11', 7, 7, 1, 'smootherStepIn')
        noteTweenX('left5', 4, 732, 0.2, 'smootherStepIn')
        noteTweenX('lefty5', 7, 1071, 0.2, 'smootherStepIn')
        noteTweenY('leftup9', 4, 570, 0.2, 'smootherStepIn')
        noteTweenY('leftup10', 7, 570, 0.2, 'smootherStepIn')
        --opponent
        noteTweenScale('opponentScale12', 0, 7, 1, 'smootherStepIn')
        noteTweenScale('opponentScale13', 3, 7, 1, 'smootherStepIn')
        noteTweenX('leftop5', 0, 92, 0.2, 'smootherStepIn')
        noteTweenX('leftyop5', 3, 431, 0.2, 'smootherStepIn')
        noteTweenY('leftupop5', 0, 570, 0.2, 'smootherStepIn')
        noteTweenY('leftupops5', 3, 570, 0.2, 'smootherStepIn')
    end

    -- lower bounce down and up
    if curStep == 687 or curStep == 693 or curStep == 703 or curStep == 719 or curStep == 735 or curStep == 751 or curStep == 767 or curStep == 783 or curStep == 799 then

        noteTweenScale('playerScale12', 5, 6, 1, 'smootherStepIn')
        noteTweenScale('playerScale13', 6, 6, 1, 'smootherStepIn')
        noteTweenX('left7', 5, 795, 0.1, 'smootherStepIn')
        noteTweenX('lefty7', 6, 908, 0.1, 'smootherStepIn')
        noteTweenY('leftup11', 5, 590, 0.1, 'smootherStepIn')
        noteTweenY('leftup12', 6, 590, 0.1, 'smootherStepIn')
        --opponent
        noteTweenScale('opponentScale14', 1, 6, 1, 'smootherStepIn')
        noteTweenScale('opponentScale15', 2, 6, 1, 'smootherStepIn')
        noteTweenX('leftyops6', 2, 388, 0.1, 'smootherStepIn')
        noteTweenY('leftupop6', 1, 590, 0.1, 'smootherStepIn')
        noteTweenY('leftupops6', 2, 590, 0.1, 'smootherStepIn')
    end

    -- original position
    if curStep == 688.9 or curStep == 694.9 or curStep == 704.9 or curStep == 720.9 or curStep == 736.9 or curStep == 752.9 or curStep == 768.9 or curStep == 784.9 or curStep == 800.9 then
        noteTweenScale('playerScale14', 5, 7, 1, 'smootherStepIn')
        noteTweenScale('playerScale15', 6, 7, 1, 'smootherStepIn')
        noteTweenX('left6', 5, 845, 0.2, 'smootherStepIn')
        noteTweenX('lefty6', 6, 958, 0.2, 'smootherStepIn')
        noteTweenY('leftup13', 5, 570, 0.2, 'smootherStepIn')
        noteTweenY('leftup14', 6, 570, 0.2, 'smootherStepIn')
        --opponent
        noteTweenScale('opponentScale16', 1, 7, 1, 'smootherStepIn')
        noteTweenScale('opponentScale17', 2, 7, 1, 'smootherStepIn')
        noteTweenX('leftop7', 1, 205, 0.2, 'smootherStepIn')
        noteTweenX('leftyop7', 2, 318, 0.2, 'smootherStepIn')
        noteTweenY('leftupop7', 1, 570, 0.2, 'smootherStepIn')
        noteTweenY('leftupops7', 2, 570, 0.2, 'smootherStepIn')
    end
end

This are the codes from the Lua I made for mid modchart

**Comment by beihu235** [comment]
I looked at the code, and I don't know where my friend got the code from, but it should be okay now, okay
