### ISSUE TITLE
File copy process

### ISSUE THREAD

**Issue by Pandaprogaming** [beihu235/FNF-NovaFlare-Engine#77]
### Describe your bug here.

I open the app and Try to press “OK” and it doesn’t respond 

### Crash Log or logcat logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

iOS

### The version number of your mobile system

18.1

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Pandaprogaming** [comment]
On this screen is where it happens
![Uploading IMG_0372.png…]()

**Comment by Pandaprogaming** [comment]
Had this issue since last 1.1.5 HOTFIX 1

**Comment by Pandaprogaming** [comment]
It will also crash on relaunch

**Comment by TEDDDDYYYYYYY** [comment]
extract the ipa and go in to assets folder (nf engine 1.1.5 hotfix 3 cus 1.1.6 crashes) then put the assets and mods folder in nf engine folder
(Sorry if explaination is bad

**Comment by beihu235** [comment]
idk if it work now, pls try again

**Comment by angeleljefe1083** [comment]
A mi me pasaba eso y no me aparecía eso no se como no me aparece esa ventana que dice de copiar todas las cosas pero hice eso y me sirvió

**Comment by Pandaprogaming** [comment]
> extract the ipa and go in to assets folder (nf engine 1.1.5 hotfix 3 cus 1.1.6 crashes) then put the assets and mods folder in nf engine folder
> 
> (Sorry if explaination is bad

Didn't work

**Comment by Pandaprogaming** [comment]
> idk if it work now, pls try again

I'll try

**Comment by MaoPou** [comment]
Waiting for the fix or using the version you can use, we currently do not have an iOS device to test and cannot fix it for the time being.

**Comment by MaoPou** [comment]
#78

**Comment by MaoPou** [comment]
Please add a comma after line 136 of assets/shader/language/English/options.json

**Comment by MaoPou** [comment]
If there are still problems please report because most crash issues are because of this comma.

**Comment by Pandaprogaming** [comment]
> idk if it work now, pls try again

The button still doesn't respond

**Comment by MaoPou** [comment]
This issue is similar on Android phones, and I've tried and come up with the following workaround (for Android, but I'm not sure if iOS works, you can try it.)
1.Go to Permissions Management, turn off all permissions for NF and put it in the background.
2.Open NF, remember, don't click any button after opening.
3.Put the NF in the background and go back to Permissions Management.
4.All permissions are granted.
5.Tap the button again to enter the NF.

If it still doesn't work, then wait until we have an iOS device to test and fix this puzzling problem

**Comment by MaoPou** [comment]
https://github.com/beihu235/FNF-NovaFlare-Engine/actions/runs/11736127871，这个版本是默认关闭文件复制的，如果还是没办法，那就看我们什么时候能修复了
