### ISSUE TITLE
1.1.6 error

### ISSUE THREAD

**Issue by Alfacev3rd** [beihu235/FNF-NovaFlare-Engine#78]
### Describe your bug here.

It keeps crashing when trying to open.

### Are you modding a build from source or with Lua?

Lua

### Have you open preload state?

No

### What is your build target?

Desktop (Linux, Windows or Mac)

### The version number of your mobile system

11

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by beihu235** [comment]
try download again

**Comment by Alfacev3rd** [comment]
> try download again

Its still crashing

**Comment by MaoPou** [comment]
Waiting for the fix or using the version you can use, we currently do not have an iOS device to test and cannot fix it for the time being.

**Comment by MaoPou** [comment]
I'm sorry bro, we made a grammatical mistake in the language file

**Comment by MaoPou** [comment]
![aa4349bc0cbc386c2a4e1d292b21b4d2](https://github.com/user-attachments/assets/b3850438-0044-40a7-82d7-e6e4372db90b)
See where the arrow is in the picture, and put a comma after that

**Comment by MaoPou** [comment]
This error is located in bin\assets\shared\language\English\options.json,line 136
