### ISSUE TITLE
crashes - NovaFlare engine.

### ISSUE THREAD

**Issue by Efrisofficial** [beihu235/FNF-NovaFlare-Engine#79]
### Describe your bug here.

atwhen the game files are loaded after that, it crashes on android 14 + magicOS 8.0 (my phone honor 90 lite)
![Screenshot_20241106_022231_com NovaFlareEngine](https://github.com/user-attachments/assets/fddc9ca7-5ea0-4498-a4b2-90a7d31e8411)

### Crash Log or logcat logs (if existing)

```bash
.
```

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

### The version number of your mobile system

14

### Did you edit anything in this build? If so, mention or summarize your changes.

.

**Comment by MaoPou** [comment]
You may not have moved the language files in the apk to Assets

**Comment by MaoPou** [comment]
#78

**Comment by MaoPou** [comment]
Please add a comma after line 136 of assets/shader/language/English/options.json
