### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by CaketheIV** [beihu235/FNF-NovaFlare-Engine#8]
### Describe your bug here.

Hi. Just came back after the current release, but after i downloaded the app,  the game wont open/crash. Making it unplayable. I also saw some of the people had the same problem.
Fix this if you can.

### Crash Log or logcat logs (if existing)

```bash
Nop
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not.

**Comment by beihu235** [comment]
android tools problem, There is no solution yet
