### ISSUE TITLE
Bug in iPhone

### ISSUE THREAD

**Issue by angeleljefe1083** [beihu235/FNF-NovaFlare-Engine#81]
### Describe your bug here.

![IMG_6596](https://github.com/user-attachments/assets/5cdf4011-3ca2-40ce-9a47-6a437e58b016)

https://github.com/user-attachments/assets/0d677ee6-bd01-44ca-a1a7-c073f7bc50c5

https://github.com/user-attachments/assets/9f6a0d8d-1426-49be-839c-c22896d2406d

I was extracting the assets from the same game because it wouldn't install itself and I didn't delete them or anything. I've been doing it for a long time and it always worked for me when you released a version I did that so that everything was compatible but I don't know what happened, when I open the game it crashes, I don't know if you can change it and then I installed it from my PC, I installed it again from your page and after it was installed on the iPhone the same thing happened. If you can fix it please, I don't know, it doesn't work for me.

### Crash Log or logcat logs (if existing)

```bash
Nothing appears on the screen, it just closes and when I go to the game folder there is nothing that says it has crashed, there appears a folder called crash
```

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

No

### What is your build target?

iOS

### The version number of your mobile system

18.1

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MaoPou** [comment]
#78

**Comment by MaoPou** [comment]
Please add a comma after line 136 of assets/shader/language/English/options.json
