### ISSUE TITLE
Problem running the game with wine.

### ISSUE THREAD

**Issue by Uyakik** [beihu235/FNF-NovaFlare-Engine#82]
### Describe your bug here.

 This error appears in wine, I use the Windows version, as the Linux version does not work in Arch Linux.
![screen](https://github.com/user-attachments/assets/20980695-cb4e-4683-9a6e-859a5bd34a25)

### Crash Log or logcat logs (if existing)

```bash
Invalid char 34 at position 5461.
```

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Desktop (Linux, Windows or Mac)

### The version number of your mobile system

x86_64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nop

**Comment by MaoPou** [comment]
#78

**Comment by MaoPou** [comment]
Whether you want to compile the source code or just want to open the game?

**Comment by MaoPou** [comment]
Our engine is available in a Linux version, so it's unlikely that you'll need to use wine, and the problem with wine is so specific that we can't figure out why it's reporting an error at the moment.

**Comment by MaoPou** [comment]
We can't be sure of the problem with wine, but I can safely say that running nf doesn't require any dependencies to be downloaded

**Comment by MaoPou** [comment]
But you can provide you with the problems that arise when running Arch Linux
