### ISSUE TITLE
I can not open the game pls helpp

### ISSUE THREAD

**Issue by xdczmods** [beihu235/FNF-NovaFlare-Engine#83]
### Describe your problem here.

![hellRon_satan](https://github.com/user-attachments/assets/8a139293-f1a0-46bb-9482-25ab5196583a)

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

No

### What is your build target?

Android

### The version number of your mobile system

8.0

### Did you edit anything in this build? If so, mention or summarize your changes.

SHUCKS!!!!!!!

**Comment by MaoPou** [comment]
Are you in good spirits, tell me what the specifics are.

**Comment by MaoPou** [comment]
#78
