### ISSUE TITLE
Just crashes

### ISSUE THREAD

**Issue by DiamondN1503** [beihu235/FNF-NovaFlare-Engine#84]
### Describe your bug here.

I just installed the last version of the engine and it copies the data and then just crashes, I close the gane and reopen it and it closes by itsemf, and it has all the permissions so it doesn't have to do that

### Crash Log or logcat logs (if existing)

```bash
Invalid char 34 at position 5325
/opt/hostedtoolcache/haxe/4.3.6/x64/std/haxe/format/JsonParser.invalidChar() [line 318]
/opt/hostedtoolcache/haxe/4.3.6/x64/std/haxe/format/JsonParser.parseRec() [line 96]
/opt/hostedtoolcache/haxe/4.3.6/x64/std/haxe/format/JsonParser.doParse() [line 57]
language/locales/OptionsLang.updateLang() [line 186]
language/Language.resetData() [line 23]
states/TitleState.create() [line 188]
flixel/FlxGame.switchState() [line 640]
flixel/FlxGame.update() [line 727]
flixel/FlxGame.step() [line 680]
flixel/FlxGame.onEnterFrame() [line 559]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
```

### Are you modding a build from source or with Lua?

I am not modding

### Have you open preload state?

Yes

### What is your build target?

Android

### The version number of your mobile system

14

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MaoPou** [comment]
我很快就会发布修复版

**Comment by MaoPou** [comment]
[https://github.com/beihu235/FNF-NovaFlare-Engine/releases/tag/V1.1.6-HOTFIX-1](url)
