### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LSVoiid** [beihu235/FNF-NovaFlare-Engine#87]
### What is your question?

玩个曲子 结束后 就成这样了
虽然过一会就好了（
![Screenshot_2024-12-21-19-59-45-71_e2ea35751c0006446b45ca8b515b31cd](https://github.com/user-attachments/assets/9c0ef4c2-e671-4f35-ac98-8c735e6a334e)

**Comment by MaoPou** [comment]
既然大部分时候没问题那就是没问题doge
