### ISSUE TITLE
NovaFlare Cursor died

### ISSUE THREAD

**Issue by Denyscrasav4ik** [beihu235/FNF-NovaFlare-Engine#9]
I just downloaded the new ver, and it shows regular cursor and not custom made one.
![Знімок екрана 2024-04-06 195935](https://github.com/beihu235/FNF-NovaFlare-Engine/assets/147797215/5486f940-12da-40d0-a414-88d4558d1cf6)
Yeah thats all lol.

**Comment by beihu235** [comment]
Because there's something wrong with my flixel library
